# Generated by Django 5.0.2 on 2024-04-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='child_age',
            field=models.IntegerField(verbose_name='سن کودک'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='child_name',
            field=models.CharField(max_length=100, verbose_name='نام فرزند'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='guardian_name',
            field=models.CharField(max_length=100, verbose_name='نام والدین'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='guardian_phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره موبایل والدین'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
    ]
