# Generated by Django 5.0.2 on 2024-04-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_appointmentrequest_child_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
    ]
