"""
Django settings for kinder project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

import os

import pymysql

pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-eik&sk84==6372b)sfhv6o%3gh*$mb#gb6--#745z#b9^@f^aq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_ckeditor_5',
  

    #internal app

    'home',
    'acounts',
    'site_setting',
    'child_mother',
    'kindergartenBranch',
    'Kindergarten',
]





CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar':  [
            'heading', '|', 'bold', 'italic', 'underline', 'strikethrough', 'link',
            'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', '|',
            'insertTable', 'mediaEmbed', '|', 'outdent', 'indent', '|', 'removeFormat',
            'code', 'subscript', 'superscript', 'highlight', '|', 'fontSize',
            'fontFamily', 'fontColor', 'fontBackgroundColor', 'alignment', '|',
            'undo', 'redo'
            
        ],
        'language': 'fa',  
        'height': 300,
        'width': '100%',
        'alignment': 'right',  

    },

    

    'extended': {
        'toolbar': [
            'heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'underline', 'strikethrough',
            'link', 'code', 'subscript', 'superscript', 'highlight', '|', 'insertImage',
            'bulletedList', 'numberedList', 'blockQuote', '|', 'fontSize', 'fontFamily',
            'fontColor', 'fontBackgroundColor', 'removeFormat', 'insertTable',
        ],

     'image': {
            'resizeOptions': [
                {
                    'name': 'resizeImage:original',
                    'value': None, 
                    'label': 'Original'
                },
                {
                    'name': 'resizeImage:custom',
                    'label': 'Custom',
                    'value': 'custom'
                },
                {
                    'name': 'resizeImage:40',
                    'value': '40',
                    'label': '40%'
                },
                {
                    'name': 'resizeImage:60',
                    'value': '60',
                    'label': '60%'
                }
            ],
            'toolbar': [
                'imageTextAlternative', '|', 'imageStyle:alignLeft', 'imageStyle:alignRight',
                'imageStyle:alignCenter', 'imageStyle:side', '|'
            ],
        },
    },
        'heading': {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' },
                { 'model': 'heading4', 'view': 'h4', 'title': 'Heading 4', 'class': 'ck-heading_heading4' },
                { 'model': 'heading5', 'view': 'h5', 'title': 'Heading 5', 'class': 'ck-heading_heading5' }

            ]
        },
    }


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kinder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kinder.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases





DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'kinder_db',
        'USER': 'root',
        'PASSWORD': 'Zehnepoya@123',
        'HOST': 'localhost',
        'PORT': '3306',
         'OPTIONS': {
            'charset': 'utf8mb4',
            'sql_mode': 'traditional',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

CKEDITOR_UPLOAD_PATH = "uploads/"
MEDIA_ROOT = BASE_DIR / 'uploads'
MEDIA_URL = '/medias/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')






# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'acounts.User'
