# Generated by Django 5.0.2 on 2024-03-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kindergartenclasses',
            name='image_title',
        ),
        migrations.AddField(
            model_name='kindergartenclasses',
            name='image_class',
            field=models.ImageField(default=1, upload_to='images/classimege', verbose_name='تصویر کلاس'),
            preserve_default=False,
        ),
    ]
