# Generated by Django 5.0.2 on 2024-03-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0002_remove_kindergartenclasses_image_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularteachers',
            options={'verbose_name': 'معلم محبوب', 'verbose_name_plural': 'معلمان محبوب'},
        ),
    ]
