# Generated by Django 5.0.2 on 2024-03-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0003_alter_popularteachers_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='middlebaner',
            name='image',
        ),
        migrations.AddField(
            model_name='middlebaner',
            name='description',
            field=models.CharField(default=1, max_length=500, verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='middlebaner',
            name='first_image',
            field=models.ImageField(default=1, upload_to='images/middlebaner', verbose_name='تصویر اول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='middlebaner',
            name='second_image',
            field=models.ImageField(default=1, upload_to='images/middlebaner', verbose_name='تصویر دوم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='middlebaner',
            name='therd_image',
            field=models.ImageField(default=1, upload_to='images/middlebaner', verbose_name='تصویر سوم'),
            preserve_default=False,
        ),
    ]
