# Generated by Django 5.0.2 on 2024-04-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0004_remove_middlebaner_image_middlebaner_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularteachers',
            name='teach_image',
            field=models.ImageField(default=1, upload_to='images/poputeach'),
            preserve_default=False,
        ),
    ]
