# Generated by Django 5.0.2 on 2024-04-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0005_popularteachers_teach_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularteachers',
            name='teach_image',
            field=models.ImageField(upload_to='images/poputeach', verbose_name='تصویر'),
        ),
    ]
